#!/bin/bash

currentPowerMode=`powerprofilesctl get`
if [[ "$1" = "get" ]]
then
  notify-send "Current Power Mode:" "$currentPowerMode"
  echo "$1"
  echo "Notification sent" 
elif [[ "$1" = "cicle" ]]; then
  if [[ $currentPowerMode = "balanced" ]]; then
    powerprofilesctl set performance
    notify-send "New Power Mode:" "performance"
  elif [[ $currentPowerMode = "performance" ]]; then
    powerprofilesctl set power-saver
    notify-send "New Power Mode:" "power-saver"
  else
   powerprofilesctl set balanced
    notify-send "New Power Mode:" "balanced"
  fi
else
  echo "Invalid option"
fi

